// TODO: CREATE A NEW "OBERON" CLASS WITH AT LEAST 6 PROPERTIES
//  THAT DESCRIBE OUR OBERON COHORT. MAKE SURE TO INCLUDE
//  AT LEAST THREE DIFFERENT TYPES OF DATA IN YOUR CLASS. IN A
//  SEPARATE FILE, CREATE 3 INSTANCES OF THE OBERON CLASS AND
//  PRINT OUT A STRING THAT USES AT LEAST 3 OF THOSE PROPERTIES
//  TO DESCRIBE THAT OBERON INSTANCE.

import java.util.Scanner;

public class Obereon {

    private String
}